package il.ac.mta.gm.engine.exception;

public enum ErrorCode {
    INVALID_PATH,
    FILE_NOT_FOUND,
    NOT_A_FILE,
    INVALID_EXTENSION,
    XML_READ_ERROR,
    DUPLICATE_EVENT_ID,
    INVALID_COMMISSION,
    INVALID_LMSR_PARAMETER,
    INVALID_OPTIONS_COUNT
}
